In [1]:
import pandas as pd
import numpy as np

In [3]:
%pip show pandas

Name: pandas
Version: 2.2.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
All rights reserved.

Copyright (c) 2011-2023, Open source contributors.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.

* Redistributions in binary form must reproduce the above copyright notice,
  this list of conditions and the following disclaimer in the documentation
  and/or other materials provided with the distribution.

* Neither the name of the copyright holder nor the names of its
  contributors may be used to endorse or promote products derived from
  this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: f:\examination\workspace\associate.aice\.venv\Lib\site-packages
Requires: numpy, python-dateutil, pytz, tzdata
Required-by: factor_analyzer, seaborn
Note: you may need to restart the kernel to use updated packages.

dataframe.drop() 
    원본 DataFrame을 변경하지 않고, 지정한 열이나 행을 삭제한 새 DataFrame 객체를 반환합니다.
    inplace=True 옵션설정시 원본 DataFrame 직접 수정

In [4]:
# DataFrame 생성
data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'class': [7, 8, 9]}
df = pd.DataFrame(data)

# drop() 호출하면 새로운 dataframe이 생성된다.
new_df = df.drop(columns=['class'])

print("원본 DataFrame:")
print(df)  # 'class' 열이 그대로 있음

print("\n새로운 DataFrame:")
print(new_df)  # 'class' 열이 삭제된 새로운 DataFrame

원본 DataFrame:
   A  B  class
0  1  4      7
1  2  5      8
2  3  6      9

새로운 DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

dataframe.drop()

    용도 
        인덱스(행)나 컬럼(열)의 라벨(label)을 기준으로 지정된 행이나 열을 삭제할 때 사용합니다.
        라벨에 의한 명시적으로 데이터를 제거할때 사용합니다.

In [ ]:
# 인덱스(행) 삭제
df.drop([0, 2], axis=0, inplace=True)

# 컬럼(열) 삭제
df.drop(['A', 'B'], axis=1, inplace=True)

불리언 인덱싱 
  용도
    조건에 따른 필터링에 의한 데이터를 제거할때 사용합니다. 
    특정 조건을 만족하는 행들을 선택하여 새로운 DataFrame으로 반환합니다.

In [ ]:
df = df[df['class'] > 8] # 8 이상 row 삭제제
df

   A  B  class
2  3  6      9

In [5]:
# DataFrame 생성
data = {'A': [1, 2, 3], 'B': [4, 5, 6], 'class': [7, 8, 9]}
df = pd.DataFrame(data)
df

   A  B  class
0  1  4      7
1  2  5      8
2  3  6      9

In [6]:
df['A']

0    1
1    2
2    3
Name: A, dtype: int64

In [7]:
df[df['A'] == 1]

   A  B  class
0  1  4      7

dataframe.dropna()
    DataFrame에서 결측치(NA, NaN 등)가 포함된 행 또는 열을 제거하는 데 사용됩니다.  
    기본적으로 결측치가 하나라도 포함된 행을 삭제하지만, 옵션을 통해 열을 삭제하거나 특정 조건을 설정할 수 있습니다.

    axis
        axis=0 (기본값)은 결측치가 있는 행을 제거합니다.
        axis=1은 결측치가 있는 열을 제거합니다.
    how
        'any' (기본값)은 한 개라도 결측치가 있으면 삭제합니다.
        'all' 'all'은 모든 값이 결측치인 행(또는 열)만 삭제합니다.
    thresh
        지정된 axis에 대해서 결측치가 아닌 값의 최소 개수를 지정합니다.
    subset
        특정 열에 대해서만 결측치 여부를 확인하여 삭제할 수 있습니다.
    inplace
        inplace=True로 설정하면 원본 DataFrame을 직접 수정합니다.

In [ ]:
df.dropna(axis=0, how='any')